### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by lucvanderzandt** [messagebird/dart-rest-api#2]
Hi, could you create a release using a git tag to make a release available in this repository? Thank you! 

Procedure I am following:
- Update `pubspec.yaml` and `CHANGELOG.md` to increment the version
- `git add . && git commit -m 'Bump version'`
- `git tag -a {version} -m 'Bump version'`
- `git push --follow-tag`

**Comment by Multimo** [comment]
Hello @lucvanderzandt I have bumped the version to v1.3.2 and put out a github release 🍾 If there is anything else, I might need to do relate to the dark ecosystem please let me know.

Thanks again for your work on this, really well done. I am very novice at dark but its super easy to read :)

**Comment by lucvanderzandt** [comment]
Thank you! And no problem at all :)

**Comment by lucvanderzandt** [comment]
Oh, one last thing: you'll need to tag a new release whenever you need to release the changes to the public. When I'm commiting important changes I'll clearly state this in the pull request from now on.

**Comment by lucvanderzandt** [comment]
Also, a tip: you could publish the package to [pub](https://pub.dev) for convenience. See [Publishing packages](https://dart.dev/tools/pub/publishing).
