### ISSUE TITLE
Flutter?

### ISSUE THREAD

**Issue by ghost** [messagebird/dart-rest-api#6]
Hi
What's the best way to use MB with Flutter?
Is there a SDK, lib ?

**Comment by marcelcorso** [comment]
Hey @pouledodue ! Great question. I was thinking of investigating it myself but didn't get around doing it. 
I don't think anybody tried at MessageBird. Maybe @lucvanderzandt has an idea?

**Comment by lucvanderzandt** [comment]
Hi @pouledodue, thank you for your question and thank you @marcelcorso for tagging me in this issue. I'm not sure I understand the question. Are you asking for a best practice to implement this library? Could you elaborate on your use case?

**Comment by ghost** [comment]
Hi
My use case is making voice calls from a Flutter Web app.

So from what I understand it would require
- MB JS lib that can make VOIP calls
- Dart bindings to the previous ^ using maybe : [js](https://pub.dev/packages/js)

What would be the others options?
Using something like [sip for Flutter](https://pub.dev/packages/sip_ua) and MB [SIP Trunk](https://developers.messagebird.com/docs/voice-calling/SIP-trunking/#sip-trunking)?

**Comment by marcelcorso** [comment]
For making voice calls from js we have https://www.messagebird.com/en/webrtc/. We got no dart bindings for it :-|

**Comment by ghost** [comment]
thanks @marcelcorso, first time I see this page

**Comment by ghost** [comment]
Does MB supports SIP over WebSocket (RFC 7118)
to use something like [Jssip](https://jssip.net/documentation/misc/sip_websocket/)

**Comment by marcelcorso** [comment]
@pouledodue I don't think we do. But that's maybe a better question for the support people. You can reach them at  support@messagebird.com . 

Ok. I think we kinda answered this right now so I'm going to close it.
